# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0010_auto_20160105_1307'),
        ('product', '0003_product_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='craft',
            name='gallery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='craft_gallery', to='photologue.Gallery'),
        ),
    ]
