# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_craft_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(default='xyz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='craft',
            name='craft_slug',
            field=models.SlugField(default='xyz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(default='xyz'),
            preserve_default=False,
        ),
    ]
